version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8080:8080"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/chatbot_test_script.py --master -H http://master:8080
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/chatbot_test_script.py --worker --master-host master